### ISSUE TITLE
Create GitHub workflow for executing tests on PRs before merging

### ISSUE THREAD

**Issue by gitaroktato** [gitaroktato/microservices-availability-simulator#5]

**Comment by VadimDez** [comment]
i would like to help with this issue, can you assign it to me?

**Comment by gitaroktato** [comment]
@VadimDez - great to hear that. I already started, but I'm happy to hand it over to you. Feel free to continue the work on the branch 
[python-test-workflow](https://github.com/gitaroktato/microservices-availability-simulator/tree/python-test-workflow) or create a new one. Happy hacktoberfest!

P.S. Make sure you star the repo if you see some value in it. Thanks!

**Comment by VadimDez** [comment]
Sorry forgot to unassign myself, I've seen you've almost finished it in the branch, so I'll let you finish it

**Comment by gitaroktato** [comment]
@VadimDez - OK, thanks for letting me know.
